Failure # 1 (occurred at 2025-01-27_13-43-13)
[36mray::ImplicitFunc.train()[39m (pid=68031, ip=10.12.92.124, actor_id=9e863d5d93fd14f3061172f801000000, repr=ray_tune_trainable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 375, in train
    raise skipped from exception_cause(skipped)
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 349, in entrypoint
    return self._trainable_func(
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 666, in _trainable_func
    output = fn()
             ^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/parallel_exec_2.py", line 241, in ray_tune_trainable
    train.main(config_dict=master_config, config_override=repetition_override)
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/train.py", line 863, in main
    learner = Learner(tensorboard_tracker=tracker,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/train.py", line 97, in __init__
    self.config_dicts['model']['class'])(
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'model'
